version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: doctorai-postgres
    environment:
      POSTGRES_USER: ellieene
      POSTGRES_PASSWORD: ellieene
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    networks:
      - doctorai-network

networks:
  doctorai-network:
    driver: bridge
